version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - bodyclose

issues:
  exclude-dirs:
    - vendor
  max-issues-per-linter: 50
  max-same-issues: 5
