// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {userconfig} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function ComposeSkillForm(arg1:desktop.SkillForm):Promise<string>;

export function ComposeToolForm(arg1:desktop.ToolForm):Promise<string>;

export function CreateSession(arg1:string):Promise<desktop.SessionInfo>;

export function DeleteMCP(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteTool(arg1:string):Promise<void>;

export function GetConfig():Promise<userconfig.Config>;

export function GetCost(arg1:string):Promise<desktop.CostInfo>;

export function GetHealth():Promise<desktop.HealthReport>;

export function GetMCPStatus():Promise<Array<desktop.MCPStatus>>;

export function GetPersona(arg1:string):Promise<desktop.Persona>;

export function GetSessions():Promise<Array<desktop.SessionInfo>>;

export function GetThemes():Promise<Array<desktop.ThemeInfo>>;

export function KMGraph():Promise<desktop.KMGraphData>;

export function KMHealth():Promise<desktop.KMHealth>;

export function KMIndex(arg1:string,arg2:string):Promise<void>;

export function KMPickDirectory():Promise<string>;

export function KMSearch(arg1:string,arg2:number):Promise<string>;

export function KMStatus():Promise<desktop.KMStats>;

export function ListAgents():Promise<Array<desktop.AgentInfo>>;

export function ListMCP():Promise<Array<desktop.MCPDoc>>;

export function ListSkills():Promise<Array<desktop.SkillDoc>>;

export function ListTools():Promise<Array<desktop.ToolDoc>>;

export function NewMCPTemplate():Promise<string>;

export function NewSkillTemplate():Promise<string>;

export function NewToolTemplate():Promise<string>;

export function OpenFile():Promise<desktop.FileResult>;

export function ParseSkillForm(arg1:string):Promise<desktop.SkillForm>;

export function ParseToolForm(arg1:string):Promise<desktop.ToolForm>;

export function PreviewContext(arg1:string):Promise<desktop.AgentContextPreview>;

export function RespondToolApproval(arg1:string,arg2:boolean):Promise<void>;

export function SaveAPIKey(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveMCP(arg1:string,arg2:string):Promise<void>;

export function SavePersona(arg1:string,arg2:desktop.Persona):Promise<void>;

export function SaveSkill(arg1:string,arg2:string):Promise<void>;

export function SaveTool(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function StopGeneration(arg1:string):Promise<void>;

export function SwitchAgent(arg1:string,arg2:string):Promise<void>;

export function TestMCP(arg1:string):Promise<desktop.MCPTestResult>;

export function TestTool(arg1:string,arg2:string):Promise<desktop.TestResult>;
