// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {userconfig} from '../models';
import {atfile} from '../models';

export function ActivateLicense(arg1:string):Promise<desktop.EntitlementInfo>;

export function BuiltinToolNames():Promise<Array<string>>;

export function CheckForUpdate():Promise<desktop.UpdateInfo>;

export function CloseSession(arg1:string):Promise<void>;

export function ComposeAgentForm(arg1:desktop.AgentForm):Promise<string>;

export function ComposeMCPForm(arg1:desktop.MCPForm):Promise<string>;

export function ComposeSkillForm(arg1:desktop.SkillForm):Promise<string>;

export function ComposeToolForm(arg1:desktop.ToolForm):Promise<string>;

export function ConfigPaths():Promise<Array<desktop.ConfigPath>>;

export function CreateSession(arg1:string):Promise<desktop.SessionInfo>;

export function DeleteAgent(arg1:string):Promise<void>;

export function DeleteMCP(arg1:string):Promise<void>;

export function DeleteSavedSession(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteTool(arg1:string):Promise<void>;

export function DownloadUpdate():Promise<desktop.UpdateDownloadResult>;

export function ExpandAtFiles(arg1:string):Promise<string|Array<string>>;

export function ExportSessionMarkdown(arg1:string):Promise<string>;

export function GetAuditConfig():Promise<desktop.AuditConfigView>;

export function GetConfig():Promise<userconfig.Config>;

export function GetCost(arg1:string):Promise<desktop.CostInfo>;

export function GetEntitlement():Promise<desktop.EntitlementInfo>;

export function GetHealth():Promise<desktop.HealthReport>;

export function GetMCPDashboard(arg1:string,arg2:boolean):Promise<Array<desktop.MCPDashboardEntry>>;

export function GetMCPStatus():Promise<Array<desktop.MCPStatus>>;

export function GetPersona(arg1:string):Promise<desktop.Persona>;

export function GetPolicyRules():Promise<Array<desktop.PolicyRuleView>>;

export function GetSessionMCP(arg1:string):Promise<Array<string>>;

export function GetSessions():Promise<Array<desktop.SessionInfo>>;

export function GetThemes():Promise<Array<desktop.ThemeInfo>>;

export function InstallPackage(arg1:string):Promise<void>;

export function KMGraph():Promise<desktop.KMGraphData>;

export function KMHealth():Promise<desktop.KMHealth>;

export function KMIndex(arg1:string,arg2:string):Promise<void>;

export function KMPickDirectory():Promise<string>;

export function KMSearch(arg1:string,arg2:number):Promise<string>;

export function KMStatus():Promise<desktop.KMStats>;

export function KnownModels():Promise<Record<string, Array<desktop.ModelOption>>>;

export function ListAgentDocs():Promise<Array<desktop.AgentDoc>>;

export function ListAgents():Promise<Array<desktop.AgentInfo>>;

export function ListAuditEvents(arg1:number):Promise<Array<desktop.AuditEventView>>;

export function ListMCP():Promise<Array<desktop.MCPDoc>>;

export function ListPackageOffers():Promise<Array<desktop.PackageOffer>>;

export function ListSavedSessions():Promise<Array<desktop.SavedSessionSummary>>;

export function ListSkills():Promise<Array<desktop.SkillDoc>>;

export function ListTools():Promise<Array<desktop.ToolDoc>>;

export function NewAgentTemplate():Promise<string>;

export function NewMCPTemplate():Promise<string>;

export function NewSkillTemplate():Promise<string>;

export function NewToolTemplate():Promise<string>;

export function OpenFile():Promise<desktop.FileResult>;

export function OpenPath(arg1:string):Promise<void>;

export function ParseAgentForm(arg1:string):Promise<desktop.AgentForm>;

export function ParseMCPForm(arg1:string):Promise<desktop.MCPForm>;

export function ParseSkillForm(arg1:string):Promise<desktop.SkillForm>;

export function ParseToolForm(arg1:string):Promise<desktop.ToolForm>;

export function PreviewContext(arg1:string):Promise<desktop.AgentContextPreview>;

export function ResetSession(arg1:string):Promise<void>;

export function RespondToolApproval(arg1:string,arg2:boolean):Promise<void>;

export function ResumeSavedSession(arg1:string,arg2:string):Promise<desktop.ResumeResult>;

export function RetryLastMessage(arg1:string):Promise<void>;

export function SaveAPIKey(arg1:string,arg2:string):Promise<void>;

export function SaveAgent(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveMCP(arg1:string,arg2:string):Promise<void>;

export function SavePersona(arg1:string,arg2:desktop.Persona):Promise<void>;

export function SaveSkill(arg1:string,arg2:string):Promise<void>;

export function SaveTool(arg1:string,arg2:string):Promise<void>;

export function SearchAtFiles(arg1:string):Promise<Array<atfile.Candidate>>;

export function SearchSavedSessions(arg1:string):Promise<Array<desktop.SavedSessionSummary>>;

export function SendMessage(arg1:string,arg2:string,arg3:Array<desktop.ImageAttachment>):Promise<void>;

export function SetProductVersion(arg1:string):Promise<void>;

export function SetSessionLabel(arg1:string,arg2:string):Promise<void>;

export function StopGeneration(arg1:string):Promise<void>;

export function SwitchAgent(arg1:string,arg2:string):Promise<void>;

export function SwitchSessionModel(arg1:string,arg2:string):Promise<void>;

export function TestMCP(arg1:string):Promise<desktop.MCPTestResult>;

export function TestTool(arg1:string,arg2:string):Promise<desktop.TestResult>;
