// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {userconfig} from '../models';
import {desktop} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string):Promise<string>;

export function GetConfig():Promise<userconfig.Config>;

export function GetMessages(arg1:string):Promise<Array<desktop.Message>>;

export function ListAgents():Promise<Array<desktop.AgentInfo>>;

export function SaveConfig(arg1:userconfig.Config):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;
